import Head from 'next/head'
import Image from 'next/image'
import homeStyles from '../styles/Home.module.css'
import Signin from '../components/Authentication/Signin.js'
import Signup from '../components/Authentication/Signup.js'
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'
import { Container } from '@chakra-ui/react'
import { Box } from '@chakra-ui/react'
import { Text } from '@chakra-ui/react'
import { Stack, HStack, VStack } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={homeStyles.main}>
        <Container>
          <Box>
            <Stack spacing={3}>
              <Text fontSize='5xl'>Authorize user !</Text>
            </Stack>
          </Box>
          <Box>
            <Tabs>
              {/* TabList */}
              <TabList>
                <Tab>Sign-up</Tab>
                <Tab>Sign-in</Tab>
              </TabList>
              {/* TabPanels */}
              <TabPanels>
                <TabPanel>
                  <Signup/>                
                </TabPanel>

                <TabPanel>
                  <Signin/>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </Box>
        </Container>
      </main>

      <footer className={homeStyles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={homeStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
