import Head from 'next/head'
// import Image from 'next/image'
import homeStyles from '../styles/Home.module.css'
import Signin from '../components/Authentication/Signin.js'
import Signup from '../components/Authentication/Signup.js'
import { chatState } from '../context/ChatProvider';
import { useRouter } from 'next/router';
import { useEffect } from 'react'

const Home = () => {
  const router = useRouter();
  /* @dev:: below doesn't work when put inside useEffect(), actually later 
  realized I should keep it outside useEffect() and it works then but then 
  realized why not to handle it in ChatProvider.js */

  // useEffect(() => {
  //   const { user } = chatState();
  //   if(user) {
  //     router.push('/chats');
  //   }
  // }, [router]);

  return (
    <div className={homeStyles.container}>
      <Head>
        <title>howdy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={homeStyles.main}>
      <Signup/>   
        {/* <Container>
          <Box>
            <Stack spacing={3}>
              <Text fontSize='5xl'>Authorize user !</Text>
            </Stack>
          </Box>
          <Box>
            <Tabs> */}
              {/* TabList */}
              {/* <TabList>
                <Tab>Sign-up</Tab>
                <Tab>Sign-in</Tab>
              </TabList> */}
              {/* TabPanels */}
              {/* <TabPanels>
                <TabPanel>
                  <Signup/>                
                </TabPanel>

                <TabPanel>
                  <Signin/>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </Box>
        </Container> */}
      </main>

      {/* default vercel footer */}
      {/* <footer className={homeStyles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={homeStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home;